### ISSUE TITLE
County missing from Merged.

### ISSUE THREAD

**Issue by mubaldino** [OpenSextant/Gazetteer#1]
We ran a doc through Xponents;  Found that many "Lee County" entries were missing. 
I went back to my Gazetteer run and found Lee County indeed exists in USGS transformed, but not at all in the final GeoData/Merged/ final output.

USGS1496538 Lee County      36.7054481  -83.1285285 A   ADM2    US  US  USA US51    US51.0105               USGS    1496538     name        F

I wonder if there is something too aggressive with the conflation of entries.

205 entries in transformed USGS intermediate gazetteer for grep "lee county"
189 entries in Merged.   In particular, the one above is missing.

The concern is that this may be wider spread than just the one above.

Marc

**Comment by dlutz2** [comment]
Marc;
Was this from the prebuilt release? I will see if we have a systemic issue with the conflation.

**Comment by mubaldino** [comment]
Clean checkout;  used NGA/USGS gazetteers from June, April, resp.ly. 
I will re-test using a much smaller USGS sample.  But for now I re-ran the Kettle from start last night.

More details:

12 such "Lee County" entries here:
 grep -i "lee county" ./transformed/USGS_xformed.txt  | grep ADM          

11 here.  Missing precisely the one in US51 (Virginia).
 grep -i "lee county" ./Merged/clean.txt  | grep ADM

**Comment by dlutz2** [comment]
Marc;
  Found 1 thing: The USGS data had a missing mandatory value (feature name) , which caused a null pointer and the process skipped the rest of the entries and kept going. Fixed that, new run same data shows many new records. Checking now if that fixes Lee Country syndrome.

**Comment by mubaldino** [comment]
Excellent.  That appears to have worked.
12 counties named "Lee" found.

**Comment by mubaldino** [comment]
This is wider spread than I thought, and also Linux row counts differ from Mac row counts.
// Latest source code (pulled today);  Latest gazetteers on both OS.  
Sorry I have not had a chance to look into row counts on Windows.

Dave, you claimed you fixed the issue; presumably tested on Windows, right?
No problems with missing data on Mac.  But I have run this all on Linux boxes.... until now, and I think that is where the issue is.  More specifically, "Transformed" phase is fine, but the "clean" phase is the first time where differences show up.   

I search for a feature type and then grep for USGS specifically to ensure row counts are consistent across platforms and across data sets.

## SAME on ALL OS

grep  "ADM" transformed/USGS_xformed.txt | grep USGS | wc
   97428
grep  "PPL" transformed/USGS_xformed.txt | grep USGS | wc
 301649

## DIFFERENCES 

MAC/WIN (?)
grep  "PPL" Merged/clean.txt  | grep USGS | wc
  253475

LINUX
grep  "PPL" Merged/clean.txt  | grep USGS | wc
   251799

Overall 
grep USGS Merged/clean.txt  
  2.50 million on Linux
  2.52 million on Mac/Win

Conclusion -- For "PPL" alone, USGS data in clean or Merged output is off by 1500 rows;  and overall I found roughly 20,000 rows for all USGS.

looking at Kettle flows on Mac now.

**Comment by dlutz2** [comment]
Just ran the flows on just the USGS data from 01 June 2016 (the released data)
I see (total row counts)
USGS to Universal step
  2,896,806 written to USGS_xformed.txt
Error Checking step
  2,896,806 - read in
  2,522,084 - written to merged/clean.txt
     232,971 - written to errors.log
     141,753 - written to duplicates.log

**Comment by dlutz2** [comment]
Also,  from Error Checking
  PPL only - 253,472 written to merged/clean.txt (off by 3?)

**Comment by dlutz2** [comment]
Question: 
"on Linux" means Kettle run and grep done on Linux, yes?
Could we try grepping the data created on Linux on a Mac to see if the differences still appear?

**Comment by mubaldino** [comment]
Correct.
To be clear -- I'm not copying data or code between OS platforms.  I am running each of these commands on each platform, to avoid any kind of corruption:

git pull  ...
ant build ...
grep ...  | wc ...

etc.

**Comment by mubaldino** [comment]
## Notes
- in experimentating and debugging Kettle project files, I find that the new serialized files saved by Kettle 6 are substantially different than these that are checked in.  Lots of XML escapes, and other adjustments.
- tried to reproduce the same result on Mac and then Linux  -- failed.  
- Updated NGA/USGS data and tried starting fresh -- failed: Lee County no longer was saved to output.  Revelation:  (Duh!) look in duplicate log output
- Experimentation -- try very, very small data set with names similar to "Lee County" for example. Small number of NGA rows and USGS rows.  Confused -- Lee County entries that were omitted during de-dup were no longer omitted.

Once I realized this was something tied to the  de-dup, I tried to enable more debugging, ala, 
-level Basic | Debug | Detailed | Rowlevel  ... this quickly became impossible.  Rowlevel debug was needed on just the aspects related to row removal (e.g., dedup, validate, clean, etc.). That level of debugging sucked up an hour of wait time watching WordStats and other things load.

## New experiment with CONFLATE_KEY

At this point I was knee deep in learning Kettle/PDI, so I thought I'd get further into it. 
The facts I could pin down was that the transformed/USGS_xformed.txt file has the intermediate output.  ./Merged/clean.txt showed inconsistently rows were removed.   So I concluded that the ErrorChecking.ktr transform that reads the former and produces the later is obviously the culprit.

The Dedup routine makes use of CONFLATE_KEY to determine duplicates. 
Indeed there are 140K true dups of nonsense in the USGS data -- so this is helpful.  But there were 20K items that were falsely being removed.    This experiment below had the right effect, but I'm still not clear why it is different from the code that was there:
- CONFLATE_KEY is a String type, not Integer
- CONFLATE_KEY as created by "Create Conflate Key" uses  name/feat/lat/lon  instead of name/cc/feat/lat/lon.    The CC seemed superfluous given the lat/lon is present.
- Use String.hashCode() as is, without casting to Long
- Carry CONFLATE_KEY on to clean.txt output file to aid in debugging de-dup aspects

So, there was no obvious way to debug this in an easy manner, e.g., push a small or partial gazetteer of 10s of rows through Kettle start to finish with debug logging on.  I started to build new Job files and tried copying in parts of transforms to emulate smaller unit tests on intermediate steps.... 

I can only think with the 17 million gazetteer entries, Kettle is trying to create a HashSet(CONFLATE_KEY)  where that key is a String.hashCode() (32 bit int) ... 
Are there ID collisions? 
These things are deterministic and should not vary across versions of Java or OS.

still scratching my head.  Below is the crux of what worked for me on both OS:

## ErrorChecking.ktr

```
    // get the feature type
    String feat = get(Fields.In, "FEATURE_CODE").getString(r);

    // ALT CONFLATE_KEY:  name;type;lat;lon,
    //   then ouput hashcode as String (instead of Int), mainly because in the future if
    //   de-duplication IDs are string hash IDs instead of Int, string is more adaptable
    //
    Object[] args = {name.replace(" ","_"), feat, lat, lon};
    String key = String.format("%s;%s;%2.4f;%3.4f", args);

    // Set conflate_key field
    get(Fields.Out, "CONFLATE_KEY").setValue(r, String.valueOf(key.hashCode()));
```

**Comment by dlutz2** [comment]
Did some experiments to compare existing hash-of-concated-string as conflate key to just using concated string  as conflate key. As you surmised, the hash-of-concated-string approach is flawed. Attached is the kettle script for the experiment which tries both ways of creating the conflate key and then finding where there conflate decision differs. The experiment found about 79,000 instances (NGA+USGS)  where the hash based approach conflated records incorrectly. The errors stem from hash collisions i.e.  a 32 bit hash does not have a big enough hash space to handle 10Ms of records.
Using the concated string itself as key is fine except that it requires either a lot more memory or the use of the slower disk-based sort and group-by steps. I will make those changes using the disk-based steps.
Did not see Lee County in the error sets but the hash-collisions are random so depend on the total data sets used.
Remove ".txt" from script name.
[ConflateTest.ktr.txt](https://github.com/OpenSextant/Gazetteer/files/428454/ConflateTest.ktr.txt)

**Comment by dlutz2** [comment]
Just committed the updated ErrorChecking script.  Still unclear why there is a platform difference.  HashCode() is a "native" method, maybe something there. Maybe Oracle JDK vs Open JDK? Just guessing. 
Anyway not using HashCode() anymore.

**Comment by dsmiley** [comment]
Ouch; who's bug?  I'm guessing this was done because maybe Kettle doesn't have a disk-resident de-dup'er and thus it won't scale (i.e. would use gobs of memory)?  Just guessing.  That's the kind of thing I would expect/want out of an ETL tool.

p.s. Lucene has to tackle this internally -- it has a disk based sorter (similar requirement to dedup) when the sort task would use too much memory.  

If we wanted to develop a disk based de-duper, you might use a mini Lucene index with one indexed StringField (no tokenization). To avoid committing after every single document (anti-pattern -- slow), you'd have a simple HashSet capped at maybe 1000 before flushing to Lucene that is consulted in conjunction with the Lucene index.

**Comment by dsmiley** [comment]
Adding to my do-it-ourselves remark, Lucene's custom "BloomFilteringPostingsFormat" (using a Bloom Filter) over the default would be especially perfect for this use-case of simple term lookup existence.

**Comment by dlutz2** [comment]
My bug. My malfunction was hashing the big strings to an integer and thinking "I will change that to a 64 bit hash when I get the rest of this working" and then forgetting about it. 
Kettle has a disk-based deduper (not sure what it uses under the covers). I switched to using that with the big strings unhashed.

**Comment by mubaldino** [comment]
That works. 
thanks,
marc
